# Generated by Django 5.0 on 2023-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('count', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('yesterday_price', models.CharField(max_length=30)),
                ('first_price', models.CharField(max_length=30)),
                ('last_trade', models.CharField(max_length=30)),
                ('close', models.CharField(max_length=30)),
                ('low', models.CharField(max_length=30)),
                ('high', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('date', 'close')},
            },
        ),
    ]
